import {
  meta,
  shopify,
  starbucks,
  tesla,
  mince,
  self,
  tv1prime,
  qt,
  tv1,
} from '../assets/images';
import {
  car,
  contact,
  css,
  estate,
  express,
  git,
  github,
  html,
  javascript,
  linkedin,
  mongodb,
  motion,
  mui,
  nextjs,
  nodejs,
  pricewise,
  react,
  redux,
  sass,
  snapgram,
  summiz,
  tailwindcss,
  threads,
  typescript,
  soundon,
  soundoff,
  docker,
  reactnative,
  shadcnui,
  springboot,
  saas,
  grocery,
  sub,
  build,
  expense,
  recipe,
} from '../assets/icons';

export const skills = [
  {
    imageUrl: css,
    name: 'CSS',
    type: 'Frontend',
  },
  {
    imageUrl: express,
    name: 'Express',
    type: 'Backend',
  },
  {
    imageUrl: git,
    name: 'Git',
    type: 'Version Control',
  },
  {
    imageUrl: github,
    name: 'GitHub',
    type: 'Version Control',
  },
  {
    imageUrl: html,
    name: 'HTML',
    type: 'Frontend',
  },
  {
    imageUrl: javascript,
    name: 'JavaScript',
    type: 'Frontend',
  },
  {
    imageUrl: mongodb,
    name: 'MongoDB',
    type: 'Database',
  },
  {
    imageUrl: motion,
    name: 'Motion',
    type: 'Animation',
  },
  {
    imageUrl: mui,
    name: 'Material-UI',
    type: 'Frontend',
  },
  {
    imageUrl: nextjs,
    name: 'Next.js',
    type: 'Frontend',
  },
  {
    imageUrl: nodejs,
    name: 'Node.js',
    type: 'Backend',
  },
  {
    imageUrl: react,
    name: 'React',
    type: 'Frontend',
  },
  {
    imageUrl: redux,
    name: 'Redux',
    type: 'State Management',
  },
  {
    imageUrl: sass,
    name: 'Sass',
    type: 'Frontend',
  },
  {
    imageUrl: tailwindcss,
    name: 'Tailwind CSS',
    type: 'Frontend',
  },
  {
    imageUrl: docker,
    name: 'Docker',
    type: 'DevOps',
  },
  {
    imageUrl: reactnative,
    name: 'React Native',
    type: 'Mobile Development',
  },
  {
    imageUrl: shadcnui,
    name: 'ShadCN UI',
    type: 'Frontend',
  },
  {
    imageUrl: springboot,
    name: 'Spring Boot',
    type: 'Backend',
  },
];

export const experiences = [
  {
    id: 1,
    title: 'Frontend Developer',
    company_name: 'QT Global Software LTD',
    icon: qt,
    iconBg: '#000000',
    date: 'Feb 2025 - March 2026',
    points: [
      'Developed and maintained the frontend of the QT Visitor Management System using Next.js.',
      'Integrated multiple APIs to support visitor registration, QR code check-ins, host notifications, and real-time visitor tracking.',
      'Designed responsive and user-friendly interfaces to improve the overall user experience and usability of the platform.',
      'Collaborated with backend developers and project stakeholders to deliver a secure and efficient digital visitor management solution.',
    ],
  },

  {
    id: 2,
    title: 'Frontend Developer',
    company_name: 'TV1 Rwanda',
    icon: tv1,
    iconBg: '#ffffff',
    date: 'September 2025 - March 2026',
    points: [
      'Worked on TV1 PRIME, the official web platform for TV1 Rwanda, using Next.js.',
      'Integrated APIs for live TV streaming, radio broadcasting, news delivery, notifications, and media content management.',
      'Built responsive and modern user interfaces focused on performance, accessibility, and user experience.',
      'Collaborated with cross-functional teams to deliver a reliable digital platform for news and entertainment consumption.',
    ],
  },
  {
    id: 3,
    title: 'React.js & React Native Developer',
    company_name: 'Mince Tech',
    icon: mince,
    iconBg: '#a2d2ff',
    date: 'March 2023 - January 2024',
    points: [
      'Developed and maintained both web and mobile applications using React.js and React Native.',
      'Collaborated with designers, backend developers, and project teams to build responsive and user-friendly digital products.',
      'Implemented reusable components, integrated APIs, and optimized application performance across different devices.',
      'Worked as part of an RCA (Rwanda Coding Academy) hackathon team to develop innovative software solutions under tight deadlines.',
    ],
  },
];

export const socialLinks = [
  {
    name: 'Contact',
    iconUrl: contact,
    link: '/contact',
  },
  {
    name: 'GitHub',
    iconUrl: github,
    link: 'https://github.com/YourGitHubUsername',
  },
  {
    name: 'LinkedIn',
    iconUrl: linkedin,
    link: 'https://www.linkedin.com/in/YourLinkedInUsername',
  },
];

export const projects = [
  {
    iconUrl: snapgram,
    theme: 'btn-back-blue',
    name: 'Zoom Clone',
    type: 'web',
    description:
      'Built a real-time video conferencing web application using Next.js and Stream Video SDK, allowing users to create and join secure video meetings with authentication and scheduling features.',
    tech: [
      'Next.js 14',
      'Stream Video SDK',
      'Clerk Authentication',
      'Tailwind CSS',
      'Radix UI',
      'TypeScript',
    ],
    link: 'https://github.com/Jean-Aime-2023/fullstack-zoom-clone',
    visit:
      'https://fullstack-zoom-clone-3px03lfia-aimes-projects-dab472e3.vercel.app',
  },
  {
    iconUrl: recipe,
    theme: 'btn-back-yellow',
    name: 'AI Recipe Platform',
    type: 'web',
    description:
      'Built a full-stack AI-powered recipe platform where users can generate, browse, and manage recipes using generative AI. The system includes authentication, content management, and a modern UI for a smooth user experience.',
    tech: [
      'Next.js 16',
      'React 19',
      'Strapi 5 (Headless CMS)',
      'PostgreSQL',
      'Clerk Authentication',
      'Google Generative AI',
      'Tailwind CSS 4',
      'Radix UI',
      'Arcjet Security',
      'React Dropzone',
      'React PDF Renderer',
      'Sonner Notifications',
    ],
    link: 'https://github.com/Jean-Aime-2025/servd/tree/main/frontend',
    visit: 'https://servd-seven-chi.vercel.app/',
  },
  {
    iconUrl: expense,
    theme: 'btn-back-blue',
    name: 'Money Manager App',
    type: 'web',
    description:
      'Built a full-stack personal finance management system that allows users to track income and expenses, visualize financial data, and manage transactions securely with authentication and reporting features.',
    tech: [
      'React 19',
      'Vite',
      'Tailwind CSS',
      'Recharts',
      'Axios',
      'Spring Boot 3.2',
      'Spring Security',
      'JWT Authentication',
      'Spring Data JPA',
      'MySQL / PostgreSQL',
      'Apache POI (Excel Export)',
      'Brevo Email API',
    ],
    link: 'https://github.com/Jean-Aime-2025/money-manager-client',
    visit: 'https://money-manager-client-nine.vercel.app/',
  },
  {
    iconUrl: build,
    theme: 'btn-back-pink',
    name: 'iBuiltThis (Project Showcase Platform)',
    type: 'web',
    description:
      'Built a modern community platform where creators can share, discover, and showcase their apps, AI tools, SaaS products, and creative projects. The platform supports project submissions, browsing feeds, and engagement between builders.',
    tech: [
      'Next.js 16',
      'React 19',
      'Clerk Authentication',
      'Drizzle ORM',
      'Neon Database (Serverless Postgres)',
      'Tailwind CSS 4',
      'React Hook Form',
      'Zod Validation',
      'Radix UI',
      'TypeScript',
    ],
    link: 'https://github.com/Jean-Aime-2025/ibuiltthis',
    visit: 'https://ibuiltthis-five.vercel.app/',
  },
  {
    iconUrl: estate,
    theme: 'btn-back-blue',
    name: 'Kribb',
    type: 'mobile',
    description:
      'Built a modern real estate mobile application using React Native and Expo, allowing users to browse, save, and manage property listings with authentication, location features, and a clean user experience.',
    tech: [
      'React Native',
      'Expo Router',
      'Clerk Authentication',
      'Supabase',
      'Zustand',
      'React Navigation',
      'NativeWind',
      'Expo Location',
    ],
    link: 'https://github.com/Jean-Aime-2025/Kribb',
    visit: '#',
  },
  {
    iconUrl: sub,
    theme: 'btn-back-red',
    name: 'Recurrly',
    type: 'mobile',
    description:
      'Built a mobile subscription management application that helps users track, organize, and analyze recurring payments in one place with a clean and intuitive interface.',
    tech: [
      'React Native',
      'Expo Router',
      'Clerk Authentication',
      'Zustand',
      'PostHog Analytics',
      'NativeWind',
    ],
    link: 'https://github.com/Jean-Aime-2025/Recurrly',
    visit: '#',
  },
  {
    iconUrl: grocery,
    theme: 'btn-back-green',
    name: 'Grocify',
    type: 'mobile',
    description:
      'Built a full-stack smart grocery list application that allows users to create, manage, and organize shopping lists efficiently with real-time syncing and secure authentication.',
    tech: [
      'React Native',
      'Expo Router',
      'Clerk Authentication',
      'Drizzle ORM',
      'Neon Database',
      'Zustand',
      'Sentry',
      'NativeWind',
    ],
    link: 'https://github.com/Jean-Aime-2025/GROCIFY',
    visit: '#',
  },
  {
    iconUrl: saas,
    theme: 'btn-back-blue',
    name: 'Light SaaS Landing Page',
    type: 'web',
    description:
      'Built a modern SaaS landing page with a clean light theme, focusing on conversion-driven UI design, responsive layout, and smooth animations for marketing and product presentation.',
    tech: [
      'Next.js 14',
      'React 18',
      'Tailwind CSS',
      'Framer Motion',
      'TypeScript',
    ],
    link: 'https://github.com/Jean-Aime-2023/light-saas-landing-ui',
    visit: 'https://light-saas-landing-ui.vercel.app',
  },
  {
    iconUrl: saas,
    theme: 'btn-back-black',
    name: 'Dark SaaS Landing Page',
    type: 'web',
    description:
      'Built a modern dark-themed SaaS landing page template with smooth animations and responsive UI components designed for startups and product marketing websites.',
    tech: [
      'Next.js 14',
      'React 18',
      'Tailwind CSS',
      'Framer Motion',
      'TypeScript',
    ],
    link: 'https://github.com/Jean-Aime-2023/Saas-UI',
    visit: 'https://saas-ui-eight.vercel.app/',
  },
  {
    iconUrl: saas,
    theme: 'btn-back-green',
    name: 'Hilink',
    type: 'web',
    description:
      'Built a modern travel landing page with a clean UI, focusing on destination browsing, responsive design, and smooth user experience for showcasing travel services.',
    tech: [
      'Next.js',
      'React',
      'Tailwind CSS',
      'Responsive Design',
      'UI/UX Design',
    ],
    link: 'https://github.com/Jean-Aime-2023/NEXTJS-TRAVEL-APP',
    visit: 'https://gilded-moonbeam-660679.netlify.app/',
  },
  {
    iconUrl: saas,
    theme: 'btn-back-red',
    name: 'Nike Landing Page',
    type: 'web',
    description:
      'Built a modern Nike-inspired landing page with a strong focus on branding, animations, and responsive UI design for product marketing.',
    tech: [
      'React',
      'Vite',
      'Tailwind CSS',
      'Responsive UI',
    ],
    link: 'https://github.com/Jean-Aime-2023/Nike-website',
    visit: 'https://golden-squirrel-895220.netlify.app/',
  },
  {
    iconUrl: saas,
    theme: 'btn-back-yellow',
    name: 'OU-Trips',
    type: 'web',
    description:
      'Built a modern travel and tour booking landing page with destination discovery, travel search, testimonials, FAQs, and responsive sections designed to deliver an engaging user experience.',
    tech: [
      'React 18',
      'Vite',
      'AOS Animations',
      'Responsive Design',
      'UI/UX Design',
    ],
    link: 'https://github.com/Jean-Aime-2023/travel-UI',
    visit: 'https://travel-ui-five.vercel.app/',
  },
];
